// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa4LRSh9BCrbhzuX58EXNBFiLx1KoOIq0',
    appId: '1:201855370607:web:3a2f2261f29b99250cd49a',
    messagingSenderId: '201855370607',
    projectId: 'fuelmap-60989',
    authDomain: 'fuelmap-60989.firebaseapp.com',
    databaseURL: 'https://fuelmap-60989-default-rtdb.firebaseio.com',
    storageBucket: 'fuelmap-60989.firebasestorage.app',
    measurementId: 'G-ZB0KNGL58V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBlu0QwchSGK0dWAffjwLiFABuChYmzI',
    appId: '1:201855370607:android:f8f1656315b9dbb20cd49a',
    messagingSenderId: '201855370607',
    projectId: 'fuelmap-60989',
    databaseURL: 'https://fuelmap-60989-default-rtdb.firebaseio.com',
    storageBucket: 'fuelmap-60989.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsilGU7VrtYMP_gQcZ9WYrxkpUDBYsWl4',
    appId: '1:201855370607:ios:a5614a2c085852ef0cd49a',
    messagingSenderId: '201855370607',
    projectId: 'fuelmap-60989',
    databaseURL: 'https://fuelmap-60989-default-rtdb.firebaseio.com',
    storageBucket: 'fuelmap-60989.firebasestorage.app',
    iosClientId: '201855370607-td48l0rmct7osed3jm6sd0a796ieca05.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsilGU7VrtYMP_gQcZ9WYrxkpUDBYsWl4',
    appId: '1:201855370607:ios:a5614a2c085852ef0cd49a',
    messagingSenderId: '201855370607',
    projectId: 'fuelmap-60989',
    databaseURL: 'https://fuelmap-60989-default-rtdb.firebaseio.com',
    storageBucket: 'fuelmap-60989.firebasestorage.app',
    iosClientId: '201855370607-td48l0rmct7osed3jm6sd0a796ieca05.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa4LRSh9BCrbhzuX58EXNBFiLx1KoOIq0',
    appId: '1:201855370607:web:44a86f293a6d53950cd49a',
    messagingSenderId: '201855370607',
    projectId: 'fuelmap-60989',
    authDomain: 'fuelmap-60989.firebaseapp.com',
    databaseURL: 'https://fuelmap-60989-default-rtdb.firebaseio.com',
    storageBucket: 'fuelmap-60989.firebasestorage.app',
    measurementId: 'G-XW3LNJJ63M',
  );
}
